#!/bin/bash

NAME="admin_pquot"                                                           # Name of the application
DJANGODIR=/home/DockerStore/SistemaCuotas/pquotadmin                           # Django project directory
SOCKFILE=/home/DockerStore/SistemaCuotas/pquotadmin/venv/run/gunicorn.sock      # we will communicte using this unix socket
BINDADDRESS=0.0.0.0:884
USER=root                                                                    # the user to run as
GROUP=root                                                                   # the group to run as
NUM_WORKERS=1                                                                # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=pquotadmin.settings                                    # which settings file should Django use
DJANGO_WSGI_MODULE=pquotadmin.wsgi                                            # WSGI module name

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
cd $DJANGODIR
source /home/DockerStore/SistemaCuotas/pquotadmin/venv/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec /home/DockerStore/SistemaCuotas/pquotadmin/venv/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
--name $NAME \
--workers $NUM_WORKERS \
--user=$USER --group=$GROUP \
--bind=unix:$SOCKFILE \
--log-level=debug \
--log-file=-
